services:
  mysql:
    image: 'mysql:8'
    container_name: 'mysql'
    environment:
      - 'MYSQL_DATABASE=poll'
      - 'MYSQL_PASSWORD=password'
      - 'MYSQL_ROOT_PASSWORD=rootpassword'
      - 'MYSQL_USER=user'
    ports:
      - '3307:3306'
  rabbitmq:
    image: 'rabbitmq:3-management'
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
