spring:
  config:
    activate.on-profile: dev

  application.name: poll-service
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/poll?rewriteBatchedStatements=true&useTimezone=true&serverTimezone=America/Recife
    username: ${MYSQL_USER:user}
    password: ${MYSQL_PASSWORD:password}

    hikari:
      connectionTimeout: 30000
      idleTimeout: 10000
      maxLifetime: 60000
      maximumPoolSize: 8
      leakDetectionThreshold: 60000

  cloud:
    function:
      definition: voteReportSupplier
    stream:
      bindings:
        voteReportSupplier-out-0:
          destination: vote-report
          group: ${application.name}
          binder: rabbit
      binders:
        rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: ${RABBITMQ_HOST:localhost}
                port: 5672
                username: ${RABBITMQ_USERNAME:guest}
                password: ${RABBITMQ_PASSWORD:guest}
                virtual-host: /
logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: trace

beeceptor:
  client.url: https://validate-cpf.free.beeceptor.com
---
#Profile test

spring:
  config:
    activate.on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MYSQL
    username: user
    password: