server.port: 8081

spring:
  config:
    activate.on-profile: default
  application.name: poll-service
  docker:
    compose.enabled: false

  jpa:
    hibernate.ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3307}/poll?rewriteBatchedStatements=true&useTimezone=true&serverTimezone=America/Recife
    username: ${MYSQL_USER:user}
    password: ${MYSQL_PASSWORD:password}

    hikari:
      connectionTimeout: 30000
      idleTimeout: 10000
      maxLifetime: 60000
      maximumPoolSize: 8
      leakDetectionThreshold: 60000

  cloud:
    feign:
      beeceptor-url: https://validate-cpf.free.beeceptor.com
    function:
      definition: voteReportSupplier
    stream:
      bindings:
        voteReportSupplier-out-0:
          destination: vote-report
          group: ${application.name}
          binder: rabbit
      binders:
        rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: ${RABBITMQ_HOST:localhost}
                port: 5672
                username: ${RABBITMQ_USERNAME:guest}
                password: ${RABBITMQ_PASSWORD:guest}
                virtual-host: /
logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: trace

---
#Profile test

spring:
  config:
    activate.on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MYSQL
    username: user
    password:
  cloud.feign.beeceptor-url: http://localhost:9000